"""
Report generation — JSON and HTML formats for evaluation results.
PDF via ReportLab if available.
"""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any

from backend.config import settings


_HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>CV Evaluation Report — {eval_name}</title>
<style>
  body {{ font-family: 'Segoe UI', sans-serif; background:#f4f6f8; color:#222; margin:0; padding:0; }}
  header {{ background: linear-gradient(135deg,#1a237e,#283593); color:white; padding:2rem; }}
  header h1 {{ margin:0; font-size:1.8rem; }}
  header p {{ margin:0.3rem 0 0; opacity:0.85; font-size:0.95rem; }}
  .container {{ max-width:1100px; margin:2rem auto; padding:0 1rem; }}
  .card {{ background:white; border-radius:8px; box-shadow:0 2px 8px rgba(0,0,0,.08); padding:1.5rem; margin-bottom:1.5rem; }}
  .card h2 {{ margin-top:0; border-bottom:2px solid #e3e8f0; padding-bottom:.6rem; color:#1a237e; }}
  .metric-grid {{ display:grid; grid-template-columns:repeat(auto-fill,minmax(180px,1fr)); gap:1rem; }}
  .metric-box {{ background:#f0f4ff; border-left:4px solid #3f51b5; padding:.8rem 1rem; border-radius:4px; }}
  .metric-box .label {{ font-size:.75rem; text-transform:uppercase; color:#666; letter-spacing:.05em; }}
  .metric-box .value {{ font-size:1.6rem; font-weight:700; color:#1a237e; }}
  table {{ width:100%; border-collapse:collapse; font-size:.9rem; }}
  th {{ background:#1a237e; color:white; padding:.6rem 1rem; text-align:left; }}
  td {{ padding:.55rem 1rem; border-bottom:1px solid #e8ecf0; }}
  tr:hover td {{ background:#f5f7ff; }}
  .badge {{ display:inline-block; border-radius:12px; padding:.15rem .7rem; font-size:.75rem; font-weight:600; }}
  .badge-ok {{ background:#e8f5e9; color:#2e7d32; }}
  .badge-warn {{ background:#fff3e0; color:#e65100; }}
  .badge-bad {{ background:#ffebee; color:#c62828; }}
  footer {{ text-align:center; padding:2rem; color:#888; font-size:.85rem; }}
</style>
</head>
<body>
<header>
  <h1>CV Evaluation Report</h1>
  <p><strong>Run:</strong> {eval_name} &nbsp;|&nbsp; <strong>Generated:</strong> {generated_at}</p>
  <p><strong>Model:</strong> {model_info} &nbsp;|&nbsp; <strong>Dataset:</strong> {dataset_info}</p>
</header>
<div class="container">

  <div class="card">
    <h2>Baseline Metrics</h2>
    <div class="metric-grid">
      {metric_boxes}
    </div>
  </div>

  {scenario_section}

  {failure_section}

</div>
<footer>Generated by CV Testing Framework &copy; {year}</footer>
</body>
</html>
"""


def _metric_box(label: str, value: Any) -> str:
    if isinstance(value, float):
        display = f"{value:.4f}"
    else:
        display = str(value)
    return (
        f'<div class="metric-box"><div class="label">{label}</div>'
        f'<div class="value">{display}</div></div>'
    )


def _degradation_badge(pct: Any) -> str:
    if pct is None:
        return '<span class="badge">N/A</span>'
    if pct < 5:
        return f'<span class="badge badge-ok">▼ {pct:.1f}%</span>'
    elif pct < 15:
        return f'<span class="badge badge-warn">▼ {pct:.1f}%</span>'
    return f'<span class="badge badge-bad">▼ {pct:.1f}%</span>'


def generate_html_report(
    evaluation: dict,
    model_info: str = "Unknown",
    dataset_info: str = "Unknown",
    include_failures: bool = True,
    include_scenarios: bool = True,
) -> str:
    metrics = evaluation.get("metrics") or {}
    primary_metrics = {
        k: v for k, v in metrics.items()
        if k not in ("per_class_metrics", "confusion_matrix") and isinstance(v, (int, float))
    }
    metric_boxes_html = "\n".join(
        _metric_box(k.replace("_", " ").title(), v)
        for k, v in primary_metrics.items()
    )

    # Scenario section
    scenario_html = ""
    if include_scenarios:
        scenario_results = evaluation.get("scenario_results") or []
        if scenario_results:
            rows = ""
            for sr in scenario_results:
                sc_metrics = sr.get("metrics") or {}
                primary_key = next(iter(primary_metrics), None)
                sc_val = sc_metrics.get(primary_key, "N/A") if primary_key else "N/A"
                if isinstance(sc_val, float):
                    sc_val = f"{sc_val:.4f}"
                rows += (
                    f"<tr><td><strong>{sr['scenario_name']}</strong></td>"
                    f"<td>{json.dumps(sr.get('params', {}), indent=None)}</td>"
                    f"<td>{sc_val}</td>"
                    f"<td>{_degradation_badge(sr.get('degradation_pct'))}</td>"
                    f"<td>{sr.get('num_failures', 0)}</td></tr>"
                )
            scenario_html = f"""
<div class="card">
  <h2>Scenario Robustness Results</h2>
  <table>
    <tr><th>Scenario</th><th>Parameters</th><th>Primary Metric</th><th>Degradation</th><th>Failures</th></tr>
    {rows}
  </table>
</div>"""

    # Failure section
    failure_html = ""
    if include_failures:
        failure_cases = evaluation.get("failure_cases") or []
        total = evaluation.get("num_failures", len(failure_cases))
        sample = failure_cases[:20]
        rows = ""
        for fc in sample:
            rows += (
                f"<tr><td>{fc.get('image_id','')}</td>"
                f"<td>{fc.get('error_type','')}</td>"
                f"<td>{fc.get('ground_truth','')}</td>"
                f"<td>{fc.get('prediction','')}</td>"
                f"<td>{fc.get('confidence') or fc.get('iou_score') or 'N/A'}</td>"
                f"<td>{fc.get('scenario','baseline')}</td></tr>"
            )
        failure_html = f"""
<div class="card">
  <h2>Failure Cases (showing {len(sample)} of {total})</h2>
  <table>
    <tr><th>Image ID</th><th>Error Type</th><th>Ground Truth</th><th>Prediction</th><th>Score</th><th>Scenario</th></tr>
    {rows}
  </table>
</div>"""

    now = datetime.utcnow()
    html = _HTML_TEMPLATE.format(
        eval_name=evaluation.get("name", "Evaluation"),
        generated_at=now.strftime("%Y-%m-%d %H:%M UTC"),
        model_info=model_info,
        dataset_info=dataset_info,
        metric_boxes=metric_boxes_html,
        scenario_section=scenario_html,
        failure_section=failure_html,
        year=now.year,
    )
    return html


def save_report(
    evaluation: dict,
    fmt: str = "json",
    model_info: str = "Unknown",
    dataset_info: str = "Unknown",
) -> Path:
    report_dir = settings.REPORTS_DIR
    report_dir.mkdir(parents=True, exist_ok=True)
    eval_id = evaluation.get("id", "report")
    ts = datetime.utcnow().strftime("%Y%m%d_%H%M%S")

    if fmt == "html":
        html = generate_html_report(evaluation, model_info, dataset_info)
        out_path = report_dir / f"{eval_id}_{ts}.html"
        out_path.write_text(html, encoding="utf-8")
    else:
        out_path = report_dir / f"{eval_id}_{ts}.json"
        out_path.write_text(
            json.dumps(evaluation, indent=2, default=str), encoding="utf-8"
        )
    return out_path
